name: astrbot_android
description: AstrBot Android App
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.2.0+24
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # pub repo
  signale: ^0.0.9
  intl: ^0.19.0
  archive: ^4.0.7
  async: ^2.11.0
  dio: ^5.7.0
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  device_info_plus: ^11.1.1
  package_info_plus: ^8.0.0
  tar: ^2.0.0
  path: ^1.9.1
  webview_flutter: ^4.10.0
  permission_handler: ^11.3.1

  # get repo
  xterm:
    git:
      url: https://github.com/TerminalStudio/xterm.dart
      ref: master
  settings:
    git: https://github.com/nightmare-space/settings
  flutter_pty:
    git: https://github.com/TerminalStudio/flutter_pty
  global_repository:
    git: https://github.com/nightmare-space/global_repository
  behavior_api:
    git:
      url: https://github.com/nightmare-space/empty_package
      path: behavior_api
  flutter_foreground_task: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl_utils: ^2.8.7

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_intl:
  enabled: true
